parts_order: [body, hand]

parts:
  body: [
    Hips,
    Spine,
    Spine1,
    Spine2,
    Neck,
    Head,
    LeftShoulder,
    LeftUpperArm,
    LeftLowerArm,
    LeftHand,
    RightShoulder,
    RightUpperArm,
    RightLowerArm,
    RightHand,
    LeftUpperLeg,
    LeftLowerLeg,
    LeftFoot,
    LeftToeBase,
    RightUpperLeg,
    RightLowerLeg,
    RightFoot,
    RightToeBase,
  ]
  hand: [
    LeftThumb1,
    LeftThumb2,
    LeftThumb3,
    LeftIndex1,
    LeftIndex2,
    LeftIndex3,
    LeftMiddle1,
    LeftMiddle2,
    LeftMiddle3,
    LeftRing1,
    LeftRing2,
    LeftRing3,
    LeftPinky1,
    LeftPinky2,
    LeftPinky3,
    RightIndex1,
    RightIndex2,
    RightIndex3,
    RightThumb1,
    RightThumb2,
    RightThumb3,
    RightMiddle1,
    RightMiddle2,
    RightMiddle3,
    RightRing1,
    RightRing2,
    RightRing3,
    RightPinky1,
    RightPinky2,
    RightPinky3,
  ]
